services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $bundle: '@Zikula\SettingsModule\ZikulaSettingsModule'

    Zikula\SettingsModule\:
        resource: '../../*'
        exclude: '../../{bootstrap.php,Tests,vendor}'

    Zikula\SettingsModule\Api\ApiInterface\LocaleApiInterface: '@Zikula\SettingsModule\Api\LocaleApi'

    # public because installer accesses this using container
    Zikula\SettingsModule\Api\LocaleApi:
        public: true

    Zikula\SettingsModule\Listener\LocaleListener:
        arguments:
            $defaultLocale: '%locale%'
            $installed: '%installed%'
