services:
    zikula_settings_module.container.link_container:
        class: Zikula\SettingsModule\Container\LinkContainer
        arguments: ["@translator.default", "@jms_i18n_routing.router", "@zikula_permissions_module.api.permission"]
        tags:
            - { name: zikula.link_container }

    zikula_settings_module.module_listener:
        class: Zikula\SettingsModule\Listener\ModuleListener
        arguments: ["@zikula_extensions_module.api.variable", "@session"]
        tags:
            - { name: kernel.event_subscriber }

    zikula_settings_module.locale_api:
        class: Zikula\SettingsModule\Api\LocaleApi

    zikula_settings_module.listener.localized_variable_listener:
        class: Zikula\SettingsModule\Listener\LocalizedVariableListener
        arguments: ["@zikula_extensions_module.api.variable"]
        tags:
            - { name: kernel.event_subscriber }
